version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: x86
build:
  project: MoonPlus.sln
  parallel: true
  verbosity: normal
test: off
