name: build-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update g++
      run: sudo apt -y install g++-8
    - name: Test
      run: make test

